encuesta/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'first_question'

    def get_queryset(self):
        """Regresa la primera pregunta por id 1"""
        return Question.objects.filter(pk=21)


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

def vote(request, question_id):
    ultima_pregunta = 27
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
            # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "No seleccionó una opción.",
            })
    else:
        selected_choice.votes += 1
        selected_choice.save()
                # Always return an HttpResponseRedirect after successfully dealing
                # with POST data. This prevents data from being posted twice if a
                # user hits the Back button.
                #if question.id+1 ==
        if question.id == ultima_pregunta:
            return render(request, 'polls/index.html', {
            'error_message': "Sus respuestas han sido registradas.",
            })
             
        return HttpResponseRedirect(reverse('polls:detail', args=(question.id+1,)))

polls/templates/polls/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<div id="contenido">
    <img src="{% static 'polls/images/logo.png' %}" alt="ITChetumal">
    <br>
<h1>{{ question.question_text }}</h1>
<br>
{% if question.id != 21 %}
<table>
    <tr>
        <td>5</td>
        <td>4</td>
        <td>3</td>
        <td>2</td>
        <td>1</td>
    </tr>
    <tr>
        <td>Totalmente de acuerdo</td>
        <td>Parcialmente de acuerdo</td>
        <td>Indiferencia</td>
        <td>Parcialmente en desacuerdo</td>
        <td>Totalmente en desacuerdo</td>
    </tr>
</table>
<br><br>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input class="choice" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    {% endfor %}
<input type="submit" value="Votar">
</form>
</div>

{% else %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <select class="choice" name="choice" id="choice">
        {% for choice in question.choice_set.all %}
            <option value="{{ choice.id }}">{{ choice.choice_text }}</option>
        {% endfor %}
    </select> 
    <input type="submit" value="Seleccionar">
</form>
<br><br><br>
</div>
{% endif %}

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<div id="contenido">

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% if first_question %}
    <img src="{% static 'polls/images/logo.png' %}" alt="ITChetumal">
    <h1>ENCUESTA PARA DETERMINACIÓN DEL AMBIENTE DE TRABAJO</h1>
    <p>
        El propósito de esta encuesta es identificar las áreas de oportunidad que nos permitan determinar y gestionar el ambiente de trabajo colaborando para cumplir con los requerimientos del Servicio Educativo. <br><br>
        Recuerda que las respuestas son opiniones basadas en tu experiencia de trabajo, por lo tanto no hay respuestas correctas o incorrectas.<br><br>
        Por favor, te pedimos que leas cuidadosamente cada una de las preguntas y marques el número que describa mejor tu opinión, con base en la escala siguiente:<br><br>
    </p>
    <table>
        <tr>
            <td>5</td>
            <td>4</td>
            <td>3</td>
            <td>2</td>
            <td>1</td>
        </tr>
        <tr>
            <td>Totalmente de acuerdo</td>
            <td>Parcialmente de acuerdo</td>
            <td>Indiferencia</td>
            <td>Parcialmente en desacuerdo</td>
            <td>Totalmente en desacuerdo</td>
        </tr>
    </table>
    <br>
    <span><strong> De clic en comenzar encuesta</strong></span>
    <ul>
    {% for question in first_question %}
        <li><a href="{% url 'polls:detail' question.id %}"> Comenzar encuesta </a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay pregustas para responder</p>
    <img src="{% static 'polls/images/gracias.gif' %}" alt="Gracias">
    <a href="{% url 'polls:index'%}">Volver al inicio</a>
{% endif %}

</div>

polls/templates/polls/results.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">¿Votar de nuevo?</a><br><br>
<a href="http://127.0.0.1:8000/polls/">Volver al inicio</a>